name: Deploy to Azure VM

on:
  push:
    branches:
      - mainxxx  # 在推送到 main 分支时触发部署

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/clean-ddd-hub:latest .
        docker push ghcr.io/${{ github.repository_owner }}/clean-ddd-hub:latest

    - name: Deploy Docker image on VM
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.VM_SSH_KEY }}
        port: ${{ secrets.VM_PORT }}
        script: |
          # 登录 GitHub 容器注册表
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          # 停止当前运行的容器（如果有）
          docker stop clean-ddd-hub || true
          docker rm clean-ddd-hub || true
          # 删除旧镜像
          docker rmi ghcr.io/${{ github.repository_owner }}/clean-ddd-hub:latest || true
          # 拉取新镜像
          docker pull ghcr.io/${{ github.repository_owner }}/clean-ddd-hub:latest
          # 启动新容器
          docker run -d --name clean-ddd-hub -p 80:3000 ghcr.io/${{ github.repository_owner }}/clean-ddd-hub:latest
